Minor cleanups: doc fixes, and clippy suggestions
tormol/map_in_place pull request #1
Opened 2020-01-24 05:18 UTC by bpfoley

Test that this is compatible back to Rust 1.26.0 (when the add
convenience method was added to std::ptr) and add that as the
minimal supported version.

2020-01-25 14:04 UTC, tormol requested changes
Wow, I had pretty much forgotten about this library! :smiley:

I'm not sure getting clippy-clean is worth increasing minimum supported rust version on it's own,
but I can add some new features to make it worth it.
(I had originally planned to rename this crate to something more generic once I finished a couple features I had started on, but since it's already being used I'll keep using the current name.)

Github won't let me add comments to unchanged parts of the file, but clippy also points out that wrapping the rustdoc example in `fn main()` is unnecessary, which you can also fix if you want.

2020-01-25 14:04 UTC, tormol commented on README.md
> +First, `malloc` and `free` takes the alignment of the types you want to store,
Now that std::alloc exists we can use std's names for the functions.
```suggestion
First, `alloc()` and `dealloc()` takes both the size and the alignment of the types you want to store,
```

2020-01-25 14:04 UTC, tormol commented on Cargo.toml
> +rust = "1.26.0"
package.rust isn't even recognized by nightly yet, and when any too old version that would benefit from it won't use it, specifying it here doesn't seem worth the "unknown manifest key" warning.

Instead it would be better to document the MSRV in the readme and rustdoc, where people are more likely to see it.
For 0.x versions i like to treat increasing required Rust version as a breaking change. and then I think we should take the opportunity to increase it to something more recent. Maybe 1.36? (the version available in Debian 10)

2020-01-27 06:40 UTC, bpfoley commented on Cargo.toml
> +rust = "1.26.0"
Oh, I didn't realize it wasn't a stable feature yet. I'll remove it and document whatever you decide on.

Unless I'm misreading, Debian Buster has rust 1.34.2, so maybe 1.34 would be a good version. https://packages.debian.org/buster/rustc

2020-02-09 12:52 UTC, tormol commented on Cargo.toml
> +rust = "1.26.0"
You're right!
(I have 1.36 as MSRV for another library, and assumed Debian was the reason.)

2020-02-09 12:53 UTC, merged